### ISSUE TITLE
Readme not up-to-date

### ISSUE THREAD

**Issue by William-N-Havard** [naver/tamgu#1]
Hello,

Just a small issue: the README.md file is not up-to-date.

The following line (second example) is missing a semi-colon (or at least I can't have the program running without adding it) `string sentence="Here, the burger and the tartare are delicious."` and output is different from what is shown in the commented line `[['meal',[6,9],[10,16]],['meal',[21,24],[25,32]]]`

**Comment by ClaudeRoux** [comment]
Corrected...
