### ISSUE TITLE
Recherche ultra rapide de sous chaines

### ISSUE THREAD

**Issue by barmic** [naver/tamgu#3]
Salut,

J'ai vu cette page : https://github.com/naver/tamgu/wiki/4.3-Recherche-ultra-rapide-de-sous-chaines-(fr)

Je suis assez surpris :

> Un caractère est codé sur 8 bits, ce qui nous fait: 32 caractères par bloc de 256 bits (8x32= 256).

La section 4 du wiki parle d'utf8 hors ce prérequis n'est valide que pour un sous-ensemble d'utf8.

> Sauf que si l’on tente d’effectuer une comparaison bit à bit, il faut que les séquences soient parfaitement alignées pour que ça marche.

Tu as aussi le problème d'allignement sur la sous-chaine de 32octets que tu prends. Si tu cherche 2 octets dans un tableau de 64o et qui contient la séquence à l'indice 31-32, il me semble que ton algo ne fonctionnera pas.

> Pour rechercher une sous-chaine dans une autre, on utilise souvent le strstr en C ou le std::string::find en C++. Le moins qu'on puisse dire c'est que c'est loin, très loin d'être optimal...

C'est donné de manière un peu gratuite pourquoi le moins que l'on puisse dire ? Quel est l'algo qui se trouve derrière (je ne sais pas le quel c'est, mais j'attendrais un naïf en O(nm) ce qui semble être le cas de ton algo d'ailleurs).

Dans quel contexte ton algo va être utilisé ? Il existe beaucoup d'algo de recherche comme cela qui vont avoir des propriétées différentes plus ou moins intéressantes. Les cas que tu semble décrire (rechercher 4o dans un tableau < 128o) ne pose pas vraiment de problème quelque soit l'algo. Dérouler les boucles, faire attention à ce qu'on fait des registres, sont les seuls points d'optimisation, mais ce n'est pas forcément l'optimum. Tu parle de grep a un moment, il a un contexte bien différent. Le développeur de ripgrep (une alternative à grep) avait fais un article sur la performance facile à lire et très intéressant :
https://blog.burntsushi.net/ripgrep/#literal-optimizations

Bonne continuation

**Comment by ClaudeRoux** [comment]
Bonjour,

En fait, le terme caractère ici est trompeur, j'aurais dû parler d'octet. Après tout un caractère UTF8 est composé d'un ou quatre octets au maximum. J'ai effectué de nombreux tests de comparaison avec strstr et avec std::string::find, leurs performances selon la taille de la chaine sont moins bonnes que celui que j'ai implémenté (jusqu'à 5 fois). Pour information, je développe au sein de la compagnie pour laquelle je travaille, un langage de programmation (Tamgu) dont l'objectif est la manipulation la plus efficace possible des chaines de caractère. conversion, recherche de sous-chaines etc. dans le but de faire du pré-traitement pour du TAL statistique (Traitement Automatique des Langues): traduction automatique, génération de texte etc. L'an dernier, nous avons participé à une tâche de traduction automatique des commentaires (WMT19) pour le français, le japonais et l'anglais (https://arxiv.org/abs/1907.06488) où nous sommes arrivés premier justement grâce à ces pré-traitements.
