### ISSUE TITLE
Compile error on Ubuntu 16.04

### ISSUE THREAD

**Issue by lorelupo** [naver/tamgu#4]
Hello, 

I am trying to compile Tamgu on Ubuntu 16.04 but I keep getting the following error while executing `make libs`. All previous installation commands execute  without problems. 

```
make[1]: Entering directory '/home/lupol/dev/notes/tp_ensimag/tp_tamgu/tamgu/libpython'
mkdir -p ../libobjs/linux/pytamgu
gcc -Iinclude -std=c++11 -w -c -fPIC -O3 -DUNIX   -DTamgu_REGEX -DREGEXCPP -DNOFASTTYPE -I/usr/include/python2.7 -Iinclude -I../include src/tamgupython.cxx -o ../libobjs/linux/pytamgu/tamgupython.o
src/tamgupython.cxx:76:42: error: conflicting declaration ‘basebin_hash<long unsigned int> Tamgupython::exported’
 basebin_hash<unsigned long> Tamgupython::exported;
                                          ^
In file included from src/tamgupython.cxx:68:0:
include/tamgupython.h:35:36: note: previous declaration as ‘bin_hash<long unsigned int> Tamgupython::exported’
     static bin_hash<unsigned long> exported;
                                    ^
src/tamgupython.cxx:76:42: error: declaration of ‘bin_hash<long unsigned int> Tamgupython::exported’ outside of class is not definition [-fpermissive]
 basebin_hash<unsigned long> Tamgupython::exported;
                                          ^
src/tamgupython.cxx: In static member function ‘static bool Tamgupython::InitialisationModule(TamguGlobal*, std::__cxx11::string)’:
src/tamgupython.cxx:316:69: error: no matching function for call to ‘TamguGlobal::RecordMethods(short int&, bin_hash<long unsigned int>&)’
     global->RecordMethods(Tamgupython::idtype, Tamgupython::exported);
                                                                     ^
In file included from ../include/tamgu.h:90:0,
                 from src/tamgupython.cxx:17:
../include/tamguglobal.h:983:17: note: candidate: void TamguGlobal::RecordMethods(short int, basebin_hash<long unsigned int>&)
  Exporting void RecordMethods(short type, basebin_hash<unsigned long>& exported);
                 ^
../include/tamguglobal.h:983:17: note:   no known conversion for argument 2 from ‘bin_hash<long unsigned int>’ to ‘basebin_hash<long unsigned int>&’
../include/tamguglobal.h:985:17: note: candidate: void TamguGlobal::RecordMethods(short int, short int, long unsigned int)
  Exporting void RecordMethods(short type, short name, unsigned long arity);
                 ^
../include/tamguglobal.h:985:17: note:   candidate expects 3 arguments, 2 provided
Makefile:17: recipe for target '../libobjs/linux/pytamgu/tamgupython.o' failed
make[1]: *** [../libobjs/linux/pytamgu/tamgupython.o] Error 1
make[1]: Leaving directory '/home/lupol/dev/notes/tp_ensimag/tp_tamgu/tamgu/libpython'
Makefile.in:44: recipe for target 'libs' failed
make: *** [libs] Error 2
```

## Update

I tried [this pre-compiled version](https://github.com/naver/tamgu/releases/tag/tamgu.linux) and got this error when running `tamgu`:

````
tamgu: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.27' not found (required by tamgu)
tamgu: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by tamgu)
````

**Comment by ClaudeRoux** [comment]
Hello,

The system is trying to compile the Python library, which is used to run a Python program from within Tamgu, or run a Tamgu program from within Python.
The reason it does not work is that it is looking for the directory where Python is installed.

I have written a small wiki to solve this issue: https://github.com/naver/tamgu/wiki/1.5-Compiling-Python

**Comment by ClaudeRoux** [comment]
Hello,

Shame on me, I did not commit the last version of tamgupython.h, which explains why you had this issue. Please, download the last version and it should be Ok.

**Comment by ClaudeRoux** [comment]
To compile the Python version, you might also read this Wiki: https://github.com/naver/tamgu/wiki/1.5-Compiling-Python.

**Comment by ClaudeRoux** [comment]
To compile the gui and sound libraries, download: https://github.com/clauderouxster/libs and move the two directories to tamgu.
We had to keep these libs apart for licensing reasons...

**Comment by lorelupo** [comment]
> Please, download the last version and it should be Ok.

Thank you @ClaudeRoux , I downloaded the last version then 
````
cd ./tamgu
python install.py
make all
make libs
````
and added 
````
export TAMGULIBS=/home/mypath/tamgu
export LD_LIBRARY_PATH=$TAMGULIBS:$LD_LIBRARY_PATH
export PATH=$TAMGULIBS:$PATH
````
to my bashrc. Everything went smoothly without errors, yet if I type `tamgu` it returns `tamgu: command not found`. Am I missing anything? 
Note that I did not make with the --gui option because I do not have fltk installed.

**Comment by ClaudeRoux** [comment]
Have you tried to run it from within its own directory, just to check if the executable can run and if it is there...
When you compile, the libs and the executable are stored in tamgu/bin/linux.

Your TAMGULIBS path should point to this directory: tamgu/bin/linux.

If you type: ./tamgu -e test.tmg

You should open an editor and be able to write a program...

**Comment by lorelupo** [comment]
> Your TAMGULIBS path should point to this directory: tamgu/bin/linux.

This did the trick. I was setting `TAMGULIBS=/home/me/tamgu` instead of `TAMGULIBS=/home/me/tamgu/bin/linux`. I would suggest to update this point in the wiki accordingly: https://github.com/naver/tamgu/wiki/1.3-Compiling-on-Linux#important

Thank you @ClaudeRoux for your kind help.

**Comment by ClaudeRoux** [comment]
Grazie mille per le sue osservazioni. Sono stati molto utili, non avevo notato che mancava un aggiornamento in uno dei miei file.
Spero che troviate il linguaggio di programmazione Tamgu di vostro gradimento.
Le suggerisco di leggere anche: https://github.com/naver/tamgu/wiki/1.7-Tamgu-as-a-scripting-language
E anche: https://github.com/naver/tamgu/blob/master/docs/English/tamgu%20as%20a%20shell%202.pdf
